from typing import Any, Literal, Protocol
from uuid import UUID

from ...models import AppSetting, Normalizer, OidcRoleMapping, Role, User
from ...schemas.administration import (
    MappingCreate,
    MappingPatch,
    NormalizerCreate,
    NormalizerPatch,
    UserCreate,
    UserPatch,
)


class UserAdministrationService(Protocol):
    def list(
        self,
        query: str | None,
        role_id: UUID | None,
        is_active: bool | None,
        authentication_method: Literal["local", "oidc"] | None,
        limit: int,
        offset: int,
    ) -> tuple[list[User], int]: ...

    def get(self, user_id: UUID) -> User: ...
    def create(self, data: UserCreate, actor_id: UUID) -> User: ...
    def update(self, user_id: UUID, data: UserPatch, actor_id: UUID) -> User: ...
    def delete(self, user_id: UUID, actor_id: UUID) -> None: ...
    def set_active(self, user_id: UUID, active: bool, actor_id: UUID) -> User: ...
    def set_role(
        self, user_id: UUID, role_id: UUID, managed: bool, actor_id: UUID
    ) -> User: ...
    def set_password(self, user_id: UUID, password: str, actor_id: UUID) -> User: ...


class RoleAdministrationService(Protocol):
    def list(self) -> list[Role]: ...
    def get(self, role_id: UUID) -> Role: ...
    def rename(self, role_id: UUID, name: str) -> Role: ...


class MappingAdministrationService(Protocol):
    def list(
        self, issuer: str | None, role_id: UUID | None, limit: int, offset: int
    ) -> tuple[list[OidcRoleMapping], int]: ...

    def get(self, mapping_id: UUID) -> OidcRoleMapping: ...
    def create(self, data: MappingCreate) -> OidcRoleMapping: ...
    def update(self, mapping_id: UUID, data: MappingPatch) -> OidcRoleMapping: ...
    def delete(self, mapping_id: UUID) -> None: ...


class SettingAdministrationService(Protocol):
    def list(self, category: str | None) -> list[AppSetting]: ...
    def get(self, key: str) -> AppSetting: ...
    def update(self, key: str, value: Any, version: int, actor_id: UUID) -> AppSetting: ...


class NormalizerAdministrationService(Protocol):
    def list(
        self, query: str | None, limit: int, offset: int
    ) -> tuple[list[Normalizer], int]: ...

    def get(self, normalizer_id: UUID) -> Normalizer: ...
    def create(self, data: NormalizerCreate, actor_id: UUID) -> Normalizer: ...
    def update(
        self, normalizer_id: UUID, data: NormalizerPatch, actor_id: UUID
    ) -> Normalizer: ...
    def delete(self, normalizer_id: UUID, version: int) -> None: ...
