from __future__ import annotations

from typing import Protocol
from uuid import UUID

from ...models import KafkaConnection, Source
from ...schemas.connections import (
    KafkaConnectionCreate,
    KafkaConnectionPatch,
    SourceCreate,
    SourceNormalizerUpdate,
    SourcePatch,
)


class KafkaConnectionService(Protocol):
    def list(self, query: str | None, limit: int, offset: int) -> tuple[list[KafkaConnection], int]: ...
    def get(self, connection_id: UUID) -> KafkaConnection: ...
    def create(self, data: KafkaConnectionCreate) -> KafkaConnection: ...
    def update(self, connection_id: UUID, data: KafkaConnectionPatch) -> KafkaConnection: ...
    def delete(self, connection_id: UUID) -> None: ...
    def test(self, connection_id: UUID) -> dict: ...
    def topics(self, connection_id: UUID, include_internal: bool) -> tuple[list[dict], int]: ...


class SourceService(Protocol):
    def list(self, query: str | None, connection_id: UUID | None, normalizer_id: UUID | None, is_enabled: bool | None, limit: int, offset: int) -> tuple[list[Source], int]: ...
    def get(self, source_id: UUID) -> Source: ...
    def create(self, data: SourceCreate) -> Source: ...
    def update(self, source_id: UUID, data: SourcePatch) -> Source: ...
    def delete(self, source_id: UUID) -> None: ...
    def set_normalizer(self, source_id: UUID, data: SourceNormalizerUpdate) -> Source: ...
    def enable(self, source_id: UUID) -> Source: ...
    def disable(self, source_id: UUID) -> Source: ...
