from typing import Protocol
from uuid import UUID

from ...schemas.external import (
    ExternalConnectionCreate,
    ExternalConnectionPatch,
    ExternalSourceCreate,
    ExternalSourcePatch,
)


class ExternalService(Protocol):
    def connections(self, limit: int, offset: int): ...
    def connection(self, identity: UUID): ...
    def create_connection(self, data: ExternalConnectionCreate): ...
    def update_connection(self, identity: UUID, data: ExternalConnectionPatch): ...
    def delete_connection(self, identity: UUID) -> None: ...
    def set_ca(self, identity: UUID, content: bytes) -> None: ...
    def delete_ca(self, identity: UUID) -> None: ...
    def test(self, identity: UUID): ...
    def indices(self, identity: UUID, limit: int, offset: int): ...
    def data_streams(self, identity: UUID, limit: int, offset: int): ...
    def sources(self, limit: int, offset: int): ...
    def source(self, identity: UUID): ...
    def create_source(self, data: ExternalSourceCreate): ...
    def update_source(self, identity: UUID, data: ExternalSourcePatch): ...
    def delete_source(self, identity: UUID) -> None: ...
    def enable(self, identity: UUID): ...
    def disable(self, identity: UUID): ...
