from datetime import datetime
from typing import Any, Protocol
from uuid import UUID

from ...models import AuthSession, OidcRoleMapping, Role, User


class UserRepository(Protocol):
    def find_local(self, username: str) -> User | None: ...
    def find_by_id(self, user_id: UUID) -> User | None: ...
    def find_oidc(self, issuer: str, subject: str) -> User | None: ...
    def create_local(
        self, username: str, password_hash: str, display_name: str, role_id: UUID
    ) -> User: ...
    def create_oidc(
        self,
        issuer: str,
        subject: str,
        email: str | None,
        display_name: str,
        role_id: UUID,
    ) -> User: ...
    def update_last_login(self, user: User, at: datetime) -> None: ...
    def update_oidc_role(self, user: User, role_id: UUID) -> None: ...


class RoleRepository(Protocol):
    def find_by_id(self, role_id: UUID) -> Role | None: ...
    def list_all(self) -> list[Role]: ...
    def rename(self, role: Role, name: str, at: datetime) -> None: ...


class OidcMappingRepository(Protocol):
    def find_for_issuer(self, issuer: str) -> list[OidcRoleMapping]: ...
    def list(
        self,
        issuer: str | None,
        role_id: UUID | None,
        limit: int,
        offset: int,
    ) -> tuple[list[OidcRoleMapping], int]: ...
    def find_by_id(self, mapping_id: UUID) -> OidcRoleMapping | None: ...
    def add(self, mapping: OidcRoleMapping) -> OidcRoleMapping: ...
    def update(self, mapping: OidcRoleMapping, values: dict[str, Any], at: datetime) -> None: ...
    def delete(self, mapping: OidcRoleMapping) -> None: ...


class SessionRepository(Protocol):
    def find_by_token_hash(self, token_hash: bytes) -> AuthSession | None: ...
    def create(
        self,
        user_id: UUID,
        token_hash: bytes,
        csrf_token_hash: bytes,
        authentication_method: str,
        now: datetime,
        expires_at: datetime,
    ) -> AuthSession: ...
    def revoke(self, auth_session: AuthSession, at: datetime) -> None: ...
    def touch(self, auth_session: AuthSession, at: datetime) -> None: ...
    def revoke_for_user(self, user_id: UUID, at: datetime) -> None: ...


class UnitOfWork(Protocol):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class ReadinessRepository(Protocol):
    def check(self) -> None: ...


class OidcClient(Protocol):
    async def authorization_redirect(self, request: Any, nonce: str) -> Any: ...
    async def verified_claims(self, request: Any, nonce: str) -> dict[str, Any]: ...
    def clear_handshake(self, request: Any) -> None: ...
