from collections.abc import Mapping
from datetime import datetime
from typing import Any, Protocol
from uuid import UUID

from ...models import AppSetting, Normalizer, User


class AdministrationUserRepository(Protocol):
    def list(
        self,
        query: str | None,
        role_id: UUID | None,
        is_active: bool | None,
        authentication_method: str | None,
        limit: int,
        offset: int,
    ) -> tuple[list[User], int]: ...
    def find_by_id(self, user_id: UUID) -> User | None: ...
    def find_local_by_username(self, username: str) -> User | None: ...
    def add(self, user: User) -> User: ...
    def update(self, user: User, values: Mapping[str, Any], at: datetime) -> None: ...
    def delete(self, user: User) -> None: ...


class SettingRepository(Protocol):
    def list(self, category: str | None) -> list[AppSetting]: ...
    def find_by_key(self, key: str) -> AppSetting | None: ...
    def update_value(
        self, setting: AppSetting, value: Any, version: int, actor: UUID
    ) -> AppSetting | None: ...


class NormalizerRepository(Protocol):
    def list(
        self, query: str | None, limit: int, offset: int
    ) -> tuple[list[Normalizer], int]: ...
    def find_by_id(self, normalizer_id: UUID) -> Normalizer | None: ...
    def add(self, normalizer: Normalizer) -> Normalizer: ...
    def update_versioned(
        self,
        normalizer: Normalizer,
        values: Mapping[str, Any],
        version: int,
        at: datetime,
    ) -> Normalizer | None: ...
    def delete_versioned(self, normalizer: Normalizer, version: int) -> bool: ...
    def disable_sources(self, normalizer_id: UUID, at: datetime) -> None: ...
