from collections.abc import Mapping
from datetime import datetime
from typing import Protocol
from uuid import UUID

from ...models import KafkaConnection, Source


class KafkaConnectionRepository(Protocol):
    def list(self, query: str | None, limit: int, offset: int) -> tuple[list[KafkaConnection], int]: ...
    def find_by_id(self, connection_id: UUID) -> KafkaConnection | None: ...
    def find_by_id_for_update(self, connection_id: UUID) -> KafkaConnection | None: ...
    def has_enabled_sources(self, connection_id: UUID) -> bool: ...
    def add(self, connection: KafkaConnection) -> KafkaConnection: ...
    def update(self, connection: KafkaConnection, values: Mapping[str, object], at: datetime) -> None: ...
    def delete(self, connection: KafkaConnection) -> None: ...


class SourceRepository(Protocol):
    def list(
        self,
        query: str | None,
        connection_id: UUID | None,
        normalizer_id: UUID | None,
        is_enabled: bool | None,
        limit: int,
        offset: int,
    ) -> tuple[list[Source], int]: ...
    def find_by_id(self, source_id: UUID) -> Source | None: ...
    def find_by_id_for_update(self, source_id: UUID) -> Source | None: ...
    def add(self, source: Source) -> Source: ...
    def update(self, source: Source, values: Mapping[str, object], at: datetime) -> None: ...
    def delete(self, source: Source) -> None: ...
