from typing import Protocol
from uuid import UUID

from ...models import ExternalConnection, Source


class ExternalRepository(Protocol):
    def connections(self, limit: int, offset: int) -> tuple[list[ExternalConnection], int]: ...
    def connection(self, identity: UUID, lock: bool = False) -> ExternalConnection | None: ...
    def sources(self, limit: int, offset: int) -> tuple[list[Source], int]: ...
    def source(self, identity: UUID, lock: bool = False) -> Source | None: ...
    def add(self, item: ExternalConnection | Source) -> None: ...
    def delete(self, item: ExternalConnection | Source) -> None: ...
    def disable_sources(self, identity: UUID) -> None: ...
