[INPUT]
    Name   dummy
    Tag    task13.tls-smoke
    Dummy  {"timestamp":"2026-10-01T12:00:00Z","log":"TASK-13 TLS smoke"}

[OUTPUT]
    Name                                       kafka
    Match                                      task13.*
    Brokers                                    kafka.example.org:9094
    Topics                                     task13-tls-smoke-unique-id
    Format                                     json
    Timestamp_Key                              timestamp
    Timestamp_Format                           iso8601
    rdkafka.security.protocol                  ssl
    rdkafka.enable.ssl.certificate.verification true
    rdkafka.ssl.endpoint.identification.algorithm https
    rdkafka.ssl.ca.location                    /etc/fluent-bit/certs/corporate-ca.pem
